/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitingForRouteImport } from './routes/waiting-for'
import { Route as SomedayRouteImport } from './routes/someday'
import { Route as ShoppingListRouteImport } from './routes/shopping-list'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProcessInboxRouteImport } from './routes/process-inbox'
import { Route as DoneRouteImport } from './routes/done'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskTaskIdRouteImport } from './routes/task.$taskId'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'

const WaitingForRoute = WaitingForRouteImport.update({
  id: '/waiting-for',
  path: '/waiting-for',
  getParentRoute: () => rootRouteImport,
} as any)
const SomedayRoute = SomedayRouteImport.update({
  id: '/someday',
  path: '/someday',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListRoute = ShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessInboxRoute = ProcessInboxRouteImport.update({
  id: '/process-inbox',
  path: '/process-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneRoute = DoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskTaskIdRoute = TaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/done': typeof DoneRoute
  '/process-inbox': typeof ProcessInboxRoute
  '/projects': typeof ProjectsRoute
  '/shopping-list': typeof ShoppingListRoute
  '/someday': typeof SomedayRoute
  '/waiting-for': typeof WaitingForRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/task/$taskId': typeof TaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/done': typeof DoneRoute
  '/process-inbox': typeof ProcessInboxRoute
  '/projects': typeof ProjectsRoute
  '/shopping-list': typeof ShoppingListRoute
  '/someday': typeof SomedayRoute
  '/waiting-for': typeof WaitingForRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/task/$taskId': typeof TaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/done': typeof DoneRoute
  '/process-inbox': typeof ProcessInboxRoute
  '/projects': typeof ProjectsRoute
  '/shopping-list': typeof ShoppingListRoute
  '/someday': typeof SomedayRoute
  '/waiting-for': typeof WaitingForRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/task/$taskId': typeof TaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/done'
    | '/process-inbox'
    | '/projects'
    | '/shopping-list'
    | '/someday'
    | '/waiting-for'
    | '/project/$projectId'
    | '/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/done'
    | '/process-inbox'
    | '/projects'
    | '/shopping-list'
    | '/someday'
    | '/waiting-for'
    | '/project/$projectId'
    | '/task/$taskId'
  id:
    | '__root__'
    | '/'
    | '/done'
    | '/process-inbox'
    | '/projects'
    | '/shopping-list'
    | '/someday'
    | '/waiting-for'
    | '/project/$projectId'
    | '/task/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoneRoute: typeof DoneRoute
  ProcessInboxRoute: typeof ProcessInboxRoute
  ProjectsRoute: typeof ProjectsRoute
  ShoppingListRoute: typeof ShoppingListRoute
  SomedayRoute: typeof SomedayRoute
  WaitingForRoute: typeof WaitingForRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  TaskTaskIdRoute: typeof TaskTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiting-for': {
      id: '/waiting-for'
      path: '/waiting-for'
      fullPath: '/waiting-for'
      preLoaderRoute: typeof WaitingForRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/someday': {
      id: '/someday'
      path: '/someday'
      fullPath: '/someday'
      preLoaderRoute: typeof SomedayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process-inbox': {
      id: '/process-inbox'
      path: '/process-inbox'
      fullPath: '/process-inbox'
      preLoaderRoute: typeof ProcessInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/done': {
      id: '/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof DoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$taskId': {
      id: '/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof TaskTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoneRoute: DoneRoute,
  ProcessInboxRoute: ProcessInboxRoute,
  ProjectsRoute: ProjectsRoute,
  ShoppingListRoute: ShoppingListRoute,
  SomedayRoute: SomedayRoute,
  WaitingForRoute: WaitingForRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  TaskTaskIdRoute: TaskTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
